baseurl: ""
title: Technological philosophy
subtitle: Unimportant thoughts
author: Jesper Reiche
simple_search: http://google.com/search
description: Unimportant thoughts
name: Jesper
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:title
timezone: Copenhagen
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
plugins:
  - jekyll-seo-tag


